name: CI Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # Every weekday
    - cron: '*/2 * * * 1-5'

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: |
          echo "This is a test."
    
