name: CI Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # Every weekday
    - cron: '*/30 * * * 1-5'

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: |
          echo "This is a test."
    
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: test
      - name: cat
        run: |
          git branch
